name: Deploy SonarQube on Azure VM

# Se activa manualmente desde la interfaz de GitHub
on:
  workflow_dispatch:  # Permite ejecutar manualmente el workflow desde la UI de GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

    - name: Install dependencies on VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          # Actualizar paquetes
          sudo apt update -y
          sudo apt upgrade -y

          # Instalar dependencias necesarias
          sudo apt install -y openjdk-11-jdk wget unzip

          # Descargar e instalar SonarQube
          SONARQUBE_VERSION=9.6.1.59040
          wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-$SONARQUBE_VERSION.zip
          unzip sonarqube-$SONARQUBE_VERSION.zip
          sudo mv sonarqube-$SONARQUBE_VERSION /opt/sonarqube

          # Crear un usuario para ejecutar SonarQube
          sudo useradd -r -m -U -d /opt/sonarqube -s /bin/bash sonar

          # Dar permisos al directorio
          sudo chown -R sonar:sonar /opt/sonarqube

          # Configuración básica para SonarQube
          sudo cp /opt/sonarqube/conf/sonar.properties /opt/sonarqube/conf/sonar.properties.bak
          sudo sed -i 's/#sonar.web.host=0.0.0.0/sonar.web.host=0.0.0.0/' /opt/sonarqube/conf/sonar.properties

          # Iniciar SonarQube
          sudo /opt/sonarqube/bin/linux-x86-64/sonar.sh start
        EOF
